AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM with HTTP API and Cognito Authorizer

Resources:
  HttpApiTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./endpoints
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 30
      MemorySize: 256
      Events:
        GetOpen:
          Type: HttpApi
          Properties:
            Path: /test
            Method: GET
            ApiId: !Ref HttpApi
            Auth:
              Authorizer: NONE
        GetSecure:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /secure
            Auth:
              Authorizer: OpenIdAuthorizer
        GetSecurePreflight:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: OPTIONS
            Path: /secure
            Auth:
              Authorizer: NONE

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
      Auth:
        Authorizers:
          OpenIdAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - !Ref MyUserPoolClient
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${MyUserPool}
        DefaultAuthorizer: OpenIdAuthorizer

  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true
      UsernameAttributes:
        - email

  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MyUserPoolClient
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref MyUserPool

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  HttpApiId:
    Description: Api id of HttpApi
    Value: !Ref HttpApi
  MyUserPoolId:
    Description: MyUserPool ID
    Value: !Ref MyUserPool
  MyUserPoolClientId:
    Description: MyUserPoolClient ID
    Value: !Ref MyUserPoolClient
